python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset graph_10k_50 --batch_partitions 15 >>log/cluster_gcn_graph_10k_50_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset graph_10k_50 --batch_partitions 45 >>log/cluster_gcn_graph_10k_50_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset graph_10k_50 --batch_partitions 90 >>log/cluster_gcn_graph_10k_50_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset graph_10k_50 --batch_partitions 150 >>log/cluster_gcn_graph_10k_50_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset graph_10k_50 --batch_partitions 375 >>log/cluster_gcn_graph_10k_50_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset graph_10k_50 --batch_partitions 750 >>log/cluster_gcn_graph_10k_50_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset graph_10k_50 --batch_partitions 15 >>log/cluster_ggnn_graph_10k_50_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset graph_10k_50 --batch_partitions 45 >>log/cluster_ggnn_graph_10k_50_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset graph_10k_50 --batch_partitions 90 >>log/cluster_ggnn_graph_10k_50_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset graph_10k_50 --batch_partitions 150 >>log/cluster_ggnn_graph_10k_50_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset graph_10k_50 --batch_partitions 375 >>log/cluster_ggnn_graph_10k_50_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset graph_10k_50 --batch_partitions 750 >>log/cluster_ggnn_graph_10k_50_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset graph_10k_50 --batch_partitions 15 >>log/cluster_gat_graph_10k_50_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset graph_10k_50 --batch_partitions 45 >>log/cluster_gat_graph_10k_50_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset graph_10k_50 --batch_partitions 90 >>log/cluster_gat_graph_10k_50_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset graph_10k_50 --batch_partitions 150 >>log/cluster_gat_graph_10k_50_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset graph_10k_50 --batch_partitions 375 >>log/cluster_gat_graph_10k_50_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset graph_10k_50 --batch_partitions 750 >>log/cluster_gat_graph_10k_50_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset graph_10k_50 --batch_partitions 15 >>log/cluster_gaan_graph_10k_50_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset graph_10k_50 --batch_partitions 45 >>log/cluster_gaan_graph_10k_50_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset graph_10k_50 --batch_partitions 90 >>log/cluster_gaan_graph_10k_50_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset graph_10k_50 --batch_partitions 150 >>log/cluster_gaan_graph_10k_50_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset graph_10k_50 --batch_partitions 375 >>log/cluster_gaan_graph_10k_50_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset graph_10k_50 --batch_partitions 750 >>log/cluster_gaan_graph_10k_50_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-computers --batch_partitions 15 >>log/cluster_gcn_amazon-computers_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-computers --batch_partitions 45 >>log/cluster_gcn_amazon-computers_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-computers --batch_partitions 90 >>log/cluster_gcn_amazon-computers_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-computers --batch_partitions 150 >>log/cluster_gcn_amazon-computers_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-computers --batch_partitions 375 >>log/cluster_gcn_amazon-computers_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-computers --batch_partitions 750 >>log/cluster_gcn_amazon-computers_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-computers --batch_partitions 15 >>log/cluster_ggnn_amazon-computers_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-computers --batch_partitions 45 >>log/cluster_ggnn_amazon-computers_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-computers --batch_partitions 90 >>log/cluster_ggnn_amazon-computers_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-computers --batch_partitions 150 >>log/cluster_ggnn_amazon-computers_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-computers --batch_partitions 375 >>log/cluster_ggnn_amazon-computers_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-computers --batch_partitions 750 >>log/cluster_ggnn_amazon-computers_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-computers --batch_partitions 15 >>log/cluster_gat_amazon-computers_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-computers --batch_partitions 45 >>log/cluster_gat_amazon-computers_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-computers --batch_partitions 90 >>log/cluster_gat_amazon-computers_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-computers --batch_partitions 150 >>log/cluster_gat_amazon-computers_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-computers --batch_partitions 375 >>log/cluster_gat_amazon-computers_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-computers --batch_partitions 750 >>log/cluster_gat_amazon-computers_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-computers --batch_partitions 15 >>log/cluster_gaan_amazon-computers_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-computers --batch_partitions 45 >>log/cluster_gaan_amazon-computers_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-computers --batch_partitions 90 >>log/cluster_gaan_amazon-computers_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-computers --batch_partitions 150 >>log/cluster_gaan_amazon-computers_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-computers --batch_partitions 375 >>log/cluster_gaan_amazon-computers_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-computers --batch_partitions 750 >>log/cluster_gaan_amazon-computers_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset flickr --batch_partitions 15 >>log/cluster_gcn_flickr_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset flickr --batch_partitions 45 >>log/cluster_gcn_flickr_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset flickr --batch_partitions 90 >>log/cluster_gcn_flickr_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset flickr --batch_partitions 150 >>log/cluster_gcn_flickr_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset flickr --batch_partitions 375 >>log/cluster_gcn_flickr_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset flickr --batch_partitions 750 >>log/cluster_gcn_flickr_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset flickr --batch_partitions 15 >>log/cluster_ggnn_flickr_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset flickr --batch_partitions 45 >>log/cluster_ggnn_flickr_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset flickr --batch_partitions 90 >>log/cluster_ggnn_flickr_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset flickr --batch_partitions 150 >>log/cluster_ggnn_flickr_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset flickr --batch_partitions 375 >>log/cluster_ggnn_flickr_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset flickr --batch_partitions 750 >>log/cluster_ggnn_flickr_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset flickr --batch_partitions 15 >>log/cluster_gat_flickr_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset flickr --batch_partitions 45 >>log/cluster_gat_flickr_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset flickr --batch_partitions 90 >>log/cluster_gat_flickr_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset flickr --batch_partitions 150 >>log/cluster_gat_flickr_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset flickr --batch_partitions 375 >>log/cluster_gat_flickr_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset flickr --batch_partitions 750 >>log/cluster_gat_flickr_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset flickr --batch_partitions 15 >>log/cluster_gaan_flickr_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset flickr --batch_partitions 45 >>log/cluster_gaan_flickr_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset flickr --batch_partitions 90 >>log/cluster_gaan_flickr_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset flickr --batch_partitions 150 >>log/cluster_gaan_flickr_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset flickr --batch_partitions 375 >>log/cluster_gaan_flickr_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset flickr --batch_partitions 750 >>log/cluster_gaan_flickr_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-photo --batch_partitions 15 >>log/cluster_gcn_amazon-photo_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-photo --batch_partitions 45 >>log/cluster_gcn_amazon-photo_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-photo --batch_partitions 90 >>log/cluster_gcn_amazon-photo_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-photo --batch_partitions 150 >>log/cluster_gcn_amazon-photo_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-photo --batch_partitions 375 >>log/cluster_gcn_amazon-photo_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset amazon-photo --batch_partitions 750 >>log/cluster_gcn_amazon-photo_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-photo --batch_partitions 15 >>log/cluster_ggnn_amazon-photo_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-photo --batch_partitions 45 >>log/cluster_ggnn_amazon-photo_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-photo --batch_partitions 90 >>log/cluster_ggnn_amazon-photo_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-photo --batch_partitions 150 >>log/cluster_ggnn_amazon-photo_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-photo --batch_partitions 375 >>log/cluster_ggnn_amazon-photo_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset amazon-photo --batch_partitions 750 >>log/cluster_ggnn_amazon-photo_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-photo --batch_partitions 15 >>log/cluster_gat_amazon-photo_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-photo --batch_partitions 45 >>log/cluster_gat_amazon-photo_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-photo --batch_partitions 90 >>log/cluster_gat_amazon-photo_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-photo --batch_partitions 150 >>log/cluster_gat_amazon-photo_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-photo --batch_partitions 375 >>log/cluster_gat_amazon-photo_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset amazon-photo --batch_partitions 750 >>log/cluster_gat_amazon-photo_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-photo --batch_partitions 15 >>log/cluster_gaan_amazon-photo_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-photo --batch_partitions 45 >>log/cluster_gaan_amazon-photo_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-photo --batch_partitions 90 >>log/cluster_gaan_amazon-photo_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-photo --batch_partitions 150 >>log/cluster_gaan_amazon-photo_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-photo --batch_partitions 375 >>log/cluster_gaan_amazon-photo_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset amazon-photo --batch_partitions 750 >>log/cluster_gaan_amazon-photo_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset coauthor-physics --batch_partitions 15 >>log/cluster_gcn_coauthor-physics_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset coauthor-physics --batch_partitions 45 >>log/cluster_gcn_coauthor-physics_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset coauthor-physics --batch_partitions 90 >>log/cluster_gcn_coauthor-physics_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset coauthor-physics --batch_partitions 150 >>log/cluster_gcn_coauthor-physics_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset coauthor-physics --batch_partitions 375 >>log/cluster_gcn_coauthor-physics_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset coauthor-physics --batch_partitions 750 >>log/cluster_gcn_coauthor-physics_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset coauthor-physics --batch_partitions 15 >>log/cluster_ggnn_coauthor-physics_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset coauthor-physics --batch_partitions 45 >>log/cluster_ggnn_coauthor-physics_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset coauthor-physics --batch_partitions 90 >>log/cluster_ggnn_coauthor-physics_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset coauthor-physics --batch_partitions 150 >>log/cluster_ggnn_coauthor-physics_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset coauthor-physics --batch_partitions 375 >>log/cluster_ggnn_coauthor-physics_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset coauthor-physics --batch_partitions 750 >>log/cluster_ggnn_coauthor-physics_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset coauthor-physics --batch_partitions 15 >>log/cluster_gat_coauthor-physics_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset coauthor-physics --batch_partitions 45 >>log/cluster_gat_coauthor-physics_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset coauthor-physics --batch_partitions 90 >>log/cluster_gat_coauthor-physics_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset coauthor-physics --batch_partitions 150 >>log/cluster_gat_coauthor-physics_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset coauthor-physics --batch_partitions 375 >>log/cluster_gat_coauthor-physics_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset coauthor-physics --batch_partitions 750 >>log/cluster_gat_coauthor-physics_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset coauthor-physics --batch_partitions 15 >>log/cluster_gaan_coauthor-physics_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset coauthor-physics --batch_partitions 45 >>log/cluster_gaan_coauthor-physics_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset coauthor-physics --batch_partitions 90 >>log/cluster_gaan_coauthor-physics_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset coauthor-physics --batch_partitions 150 >>log/cluster_gaan_coauthor-physics_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset coauthor-physics --batch_partitions 375 >>log/cluster_gaan_coauthor-physics_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset coauthor-physics --batch_partitions 750 >>log/cluster_gaan_coauthor-physics_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset com-amazon --batch_partitions 15 >>log/cluster_gcn_com-amazon_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset com-amazon --batch_partitions 45 >>log/cluster_gcn_com-amazon_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset com-amazon --batch_partitions 90 >>log/cluster_gcn_com-amazon_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset com-amazon --batch_partitions 150 >>log/cluster_gcn_com-amazon_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset com-amazon --batch_partitions 375 >>log/cluster_gcn_com-amazon_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset com-amazon --batch_partitions 750 >>log/cluster_gcn_com-amazon_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset com-amazon --batch_partitions 15 >>log/cluster_ggnn_com-amazon_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset com-amazon --batch_partitions 45 >>log/cluster_ggnn_com-amazon_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset com-amazon --batch_partitions 90 >>log/cluster_ggnn_com-amazon_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset com-amazon --batch_partitions 150 >>log/cluster_ggnn_com-amazon_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset com-amazon --batch_partitions 375 >>log/cluster_ggnn_com-amazon_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset com-amazon --batch_partitions 750 >>log/cluster_ggnn_com-amazon_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset com-amazon --batch_partitions 15 >>log/cluster_gat_com-amazon_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset com-amazon --batch_partitions 45 >>log/cluster_gat_com-amazon_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset com-amazon --batch_partitions 90 >>log/cluster_gat_com-amazon_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset com-amazon --batch_partitions 150 >>log/cluster_gat_com-amazon_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset com-amazon --batch_partitions 375 >>log/cluster_gat_com-amazon_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset com-amazon --batch_partitions 750 >>log/cluster_gat_com-amazon_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset com-amazon --batch_partitions 15 >>log/cluster_gaan_com-amazon_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset com-amazon --batch_partitions 45 >>log/cluster_gaan_com-amazon_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset com-amazon --batch_partitions 90 >>log/cluster_gaan_com-amazon_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset com-amazon --batch_partitions 150 >>log/cluster_gaan_com-amazon_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset com-amazon --batch_partitions 375 >>log/cluster_gaan_com-amazon_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset com-amazon --batch_partitions 750 >>log/cluster_gaan_com-amazon_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset pubmed --batch_partitions 15 >>log/cluster_gcn_pubmed_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset pubmed --batch_partitions 45 >>log/cluster_gcn_pubmed_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset pubmed --batch_partitions 90 >>log/cluster_gcn_pubmed_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset pubmed --batch_partitions 150 >>log/cluster_gcn_pubmed_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset pubmed --batch_partitions 375 >>log/cluster_gcn_pubmed_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gcn --dataset pubmed --batch_partitions 750 >>log/cluster_gcn_pubmed_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset pubmed --batch_partitions 15 >>log/cluster_ggnn_pubmed_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset pubmed --batch_partitions 45 >>log/cluster_ggnn_pubmed_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset pubmed --batch_partitions 90 >>log/cluster_ggnn_pubmed_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset pubmed --batch_partitions 150 >>log/cluster_ggnn_pubmed_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset pubmed --batch_partitions 375 >>log/cluster_ggnn_pubmed_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model ggnn --dataset pubmed --batch_partitions 750 >>log/cluster_ggnn_pubmed_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset pubmed --batch_partitions 15 >>log/cluster_gat_pubmed_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset pubmed --batch_partitions 45 >>log/cluster_gat_pubmed_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset pubmed --batch_partitions 90 >>log/cluster_gat_pubmed_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset pubmed --batch_partitions 150 >>log/cluster_gat_pubmed_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset pubmed --batch_partitions 375 >>log/cluster_gat_pubmed_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gat --dataset pubmed --batch_partitions 750 >>log/cluster_gat_pubmed_750.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset pubmed --batch_partitions 15 >>log/cluster_gaan_pubmed_15.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset pubmed --batch_partitions 45 >>log/cluster_gaan_pubmed_45.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset pubmed --batch_partitions 90 >>log/cluster_gaan_pubmed_90.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset pubmed --batch_partitions 150 >>log/cluster_gaan_pubmed_150.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset pubmed --batch_partitions 375 >>log/cluster_gaan_pubmed_375.log 2>&1
python -m code.main_sampling_graph_info --device cuda:1 --mode cluster --model gaan --dataset pubmed --batch_partitions 750 >>log/cluster_gaan_pubmed_750.log 2>&1
