python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data graph_10k_50 --epochs 50 --batch_size 100 >>log/graphsage_gcn_graph_10k_50_100.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data graph_10k_50 --epochs 50 --batch_size 300 >>log/graphsage_gcn_graph_10k_50_300.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data graph_10k_50 --epochs 50 --batch_size 600 >>log/graphsage_gcn_graph_10k_50_600.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data graph_10k_50 --epochs 50 --batch_size 1000 >>log/graphsage_gcn_graph_10k_50_1000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data graph_10k_50 --epochs 50 --batch_size 2500 >>log/graphsage_gcn_graph_10k_50_2500.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data graph_10k_50 --epochs 50 --batch_size 5000 >>log/graphsage_gcn_graph_10k_50_5000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data graph_10k_50 --epochs 50 --batch_size 100 >>log/graphsage_ggnn_graph_10k_50_100.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data graph_10k_50 --epochs 50 --batch_size 300 >>log/graphsage_ggnn_graph_10k_50_300.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data graph_10k_50 --epochs 50 --batch_size 600 >>log/graphsage_ggnn_graph_10k_50_600.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data graph_10k_50 --epochs 50 --batch_size 1000 >>log/graphsage_ggnn_graph_10k_50_1000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data graph_10k_50 --epochs 50 --batch_size 2500 >>log/graphsage_ggnn_graph_10k_50_2500.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data graph_10k_50 --epochs 50 --batch_size 5000 >>log/graphsage_ggnn_graph_10k_50_5000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data graph_10k_50 --epochs 50 --batch_size 100 >>log/graphsage_gat_graph_10k_50_100.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data graph_10k_50 --epochs 50 --batch_size 300 >>log/graphsage_gat_graph_10k_50_300.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data graph_10k_50 --epochs 50 --batch_size 600 >>log/graphsage_gat_graph_10k_50_600.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data graph_10k_50 --epochs 50 --batch_size 1000 >>log/graphsage_gat_graph_10k_50_1000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data graph_10k_50 --epochs 50 --batch_size 2500 >>log/graphsage_gat_graph_10k_50_2500.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data graph_10k_50 --epochs 50 --batch_size 5000 >>log/graphsage_gat_graph_10k_50_5000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data graph_10k_50 --epochs 50 --batch_size 100 >>log/graphsage_gaan_graph_10k_50_100.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data graph_10k_50 --epochs 50 --batch_size 300 >>log/graphsage_gaan_graph_10k_50_300.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data graph_10k_50 --epochs 50 --batch_size 600 >>log/graphsage_gaan_graph_10k_50_600.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data graph_10k_50 --epochs 50 --batch_size 1000 >>log/graphsage_gaan_graph_10k_50_1000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data graph_10k_50 --epochs 50 --batch_size 2500 >>log/graphsage_gaan_graph_10k_50_2500.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data graph_10k_50 --epochs 50 --batch_size 5000 >>log/graphsage_gaan_graph_10k_50_5000.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-computers --epochs 50 --batch_size 138 >>log/graphsage_gcn_amazon-computers_138.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-computers --epochs 50 --batch_size 413 >>log/graphsage_gcn_amazon-computers_413.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-computers --epochs 50 --batch_size 826 >>log/graphsage_gcn_amazon-computers_826.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-computers --epochs 50 --batch_size 1376 >>log/graphsage_gcn_amazon-computers_1376.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-computers --epochs 50 --batch_size 3438 >>log/graphsage_gcn_amazon-computers_3438.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-computers --epochs 50 --batch_size 6876 >>log/graphsage_gcn_amazon-computers_6876.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-computers --epochs 50 --batch_size 138 >>log/graphsage_ggnn_amazon-computers_138.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-computers --epochs 50 --batch_size 413 >>log/graphsage_ggnn_amazon-computers_413.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-computers --epochs 50 --batch_size 826 >>log/graphsage_ggnn_amazon-computers_826.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-computers --epochs 50 --batch_size 1376 >>log/graphsage_ggnn_amazon-computers_1376.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-computers --epochs 50 --batch_size 3438 >>log/graphsage_ggnn_amazon-computers_3438.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-computers --epochs 50 --batch_size 6876 >>log/graphsage_ggnn_amazon-computers_6876.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-computers --epochs 50 --batch_size 138 >>log/graphsage_gat_amazon-computers_138.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-computers --epochs 50 --batch_size 413 >>log/graphsage_gat_amazon-computers_413.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-computers --epochs 50 --batch_size 826 >>log/graphsage_gat_amazon-computers_826.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-computers --epochs 50 --batch_size 1376 >>log/graphsage_gat_amazon-computers_1376.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-computers --epochs 50 --batch_size 3438 >>log/graphsage_gat_amazon-computers_3438.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-computers --epochs 50 --batch_size 6876 >>log/graphsage_gat_amazon-computers_6876.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-computers --epochs 50 --batch_size 138 >>log/graphsage_gaan_amazon-computers_138.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-computers --epochs 50 --batch_size 413 >>log/graphsage_gaan_amazon-computers_413.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-computers --epochs 50 --batch_size 826 >>log/graphsage_gaan_amazon-computers_826.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-computers --epochs 50 --batch_size 1376 >>log/graphsage_gaan_amazon-computers_1376.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-computers --epochs 50 --batch_size 3438 >>log/graphsage_gaan_amazon-computers_3438.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-computers --epochs 50 --batch_size 6876 >>log/graphsage_gaan_amazon-computers_6876.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data flickr --epochs 50 --batch_size 893 >>log/graphsage_gcn_flickr_893.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data flickr --epochs 50 --batch_size 2678 >>log/graphsage_gcn_flickr_2678.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data flickr --epochs 50 --batch_size 5355 >>log/graphsage_gcn_flickr_5355.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data flickr --epochs 50 --batch_size 8925 >>log/graphsage_gcn_flickr_8925.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data flickr --epochs 50 --batch_size 22313 >>log/graphsage_gcn_flickr_22313.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data flickr --epochs 50 --batch_size 44625 >>log/graphsage_gcn_flickr_44625.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data flickr --epochs 50 --batch_size 893 >>log/graphsage_ggnn_flickr_893.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data flickr --epochs 50 --batch_size 2678 >>log/graphsage_ggnn_flickr_2678.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data flickr --epochs 50 --batch_size 5355 >>log/graphsage_ggnn_flickr_5355.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data flickr --epochs 50 --batch_size 8925 >>log/graphsage_ggnn_flickr_8925.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data flickr --epochs 50 --batch_size 22313 >>log/graphsage_ggnn_flickr_22313.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data flickr --epochs 50 --batch_size 44625 >>log/graphsage_ggnn_flickr_44625.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data flickr --epochs 50 --batch_size 893 >>log/graphsage_gat_flickr_893.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data flickr --epochs 50 --batch_size 2678 >>log/graphsage_gat_flickr_2678.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data flickr --epochs 50 --batch_size 5355 >>log/graphsage_gat_flickr_5355.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data flickr --epochs 50 --batch_size 8925 >>log/graphsage_gat_flickr_8925.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data flickr --epochs 50 --batch_size 22313 >>log/graphsage_gat_flickr_22313.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data flickr --epochs 50 --batch_size 44625 >>log/graphsage_gat_flickr_44625.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data flickr --epochs 50 --batch_size 893 >>log/graphsage_gaan_flickr_893.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data flickr --epochs 50 --batch_size 2678 >>log/graphsage_gaan_flickr_2678.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data flickr --epochs 50 --batch_size 5355 >>log/graphsage_gaan_flickr_5355.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data flickr --epochs 50 --batch_size 8925 >>log/graphsage_gaan_flickr_8925.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data flickr --epochs 50 --batch_size 22313 >>log/graphsage_gaan_flickr_22313.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data flickr --epochs 50 --batch_size 44625 >>log/graphsage_gaan_flickr_44625.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-photo --epochs 50 --batch_size 77 >>log/graphsage_gcn_amazon-photo_77.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-photo --epochs 50 --batch_size 230 >>log/graphsage_gcn_amazon-photo_230.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-photo --epochs 50 --batch_size 459 >>log/graphsage_gcn_amazon-photo_459.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-photo --epochs 50 --batch_size 765 >>log/graphsage_gcn_amazon-photo_765.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-photo --epochs 50 --batch_size 1913 >>log/graphsage_gcn_amazon-photo_1913.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data amazon-photo --epochs 50 --batch_size 3825 >>log/graphsage_gcn_amazon-photo_3825.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-photo --epochs 50 --batch_size 77 >>log/graphsage_ggnn_amazon-photo_77.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-photo --epochs 50 --batch_size 230 >>log/graphsage_ggnn_amazon-photo_230.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-photo --epochs 50 --batch_size 459 >>log/graphsage_ggnn_amazon-photo_459.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-photo --epochs 50 --batch_size 765 >>log/graphsage_ggnn_amazon-photo_765.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-photo --epochs 50 --batch_size 1913 >>log/graphsage_ggnn_amazon-photo_1913.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data amazon-photo --epochs 50 --batch_size 3825 >>log/graphsage_ggnn_amazon-photo_3825.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-photo --epochs 50 --batch_size 77 >>log/graphsage_gat_amazon-photo_77.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-photo --epochs 50 --batch_size 230 >>log/graphsage_gat_amazon-photo_230.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-photo --epochs 50 --batch_size 459 >>log/graphsage_gat_amazon-photo_459.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-photo --epochs 50 --batch_size 765 >>log/graphsage_gat_amazon-photo_765.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-photo --epochs 50 --batch_size 1913 >>log/graphsage_gat_amazon-photo_1913.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data amazon-photo --epochs 50 --batch_size 3825 >>log/graphsage_gat_amazon-photo_3825.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-photo --epochs 50 --batch_size 77 >>log/graphsage_gaan_amazon-photo_77.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-photo --epochs 50 --batch_size 230 >>log/graphsage_gaan_amazon-photo_230.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-photo --epochs 50 --batch_size 459 >>log/graphsage_gaan_amazon-photo_459.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-photo --epochs 50 --batch_size 765 >>log/graphsage_gaan_amazon-photo_765.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-photo --epochs 50 --batch_size 1913 >>log/graphsage_gaan_amazon-photo_1913.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data amazon-photo --epochs 50 --batch_size 3825 >>log/graphsage_gaan_amazon-photo_3825.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data coauthor-physics --epochs 50 --batch_size 345 >>log/graphsage_gcn_coauthor-physics_345.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data coauthor-physics --epochs 50 --batch_size 1035 >>log/graphsage_gcn_coauthor-physics_1035.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data coauthor-physics --epochs 50 --batch_size 2070 >>log/graphsage_gcn_coauthor-physics_2070.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data coauthor-physics --epochs 50 --batch_size 3450 >>log/graphsage_gcn_coauthor-physics_3450.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data coauthor-physics --epochs 50 --batch_size 8624 >>log/graphsage_gcn_coauthor-physics_8624.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data coauthor-physics --epochs 50 --batch_size 17247 >>log/graphsage_gcn_coauthor-physics_17247.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data coauthor-physics --epochs 50 --batch_size 345 >>log/graphsage_ggnn_coauthor-physics_345.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data coauthor-physics --epochs 50 --batch_size 1035 >>log/graphsage_ggnn_coauthor-physics_1035.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data coauthor-physics --epochs 50 --batch_size 2070 >>log/graphsage_ggnn_coauthor-physics_2070.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data coauthor-physics --epochs 50 --batch_size 3450 >>log/graphsage_ggnn_coauthor-physics_3450.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data coauthor-physics --epochs 50 --batch_size 8624 >>log/graphsage_ggnn_coauthor-physics_8624.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data coauthor-physics --epochs 50 --batch_size 17247 >>log/graphsage_ggnn_coauthor-physics_17247.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data coauthor-physics --epochs 50 --batch_size 345 >>log/graphsage_gat_coauthor-physics_345.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data coauthor-physics --epochs 50 --batch_size 1035 >>log/graphsage_gat_coauthor-physics_1035.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data coauthor-physics --epochs 50 --batch_size 2070 >>log/graphsage_gat_coauthor-physics_2070.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data coauthor-physics --epochs 50 --batch_size 3450 >>log/graphsage_gat_coauthor-physics_3450.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data coauthor-physics --epochs 50 --batch_size 8624 >>log/graphsage_gat_coauthor-physics_8624.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data coauthor-physics --epochs 50 --batch_size 17247 >>log/graphsage_gat_coauthor-physics_17247.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data coauthor-physics --epochs 50 --batch_size 345 >>log/graphsage_gaan_coauthor-physics_345.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data coauthor-physics --epochs 50 --batch_size 1035 >>log/graphsage_gaan_coauthor-physics_1035.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data coauthor-physics --epochs 50 --batch_size 2070 >>log/graphsage_gaan_coauthor-physics_2070.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data coauthor-physics --epochs 50 --batch_size 3450 >>log/graphsage_gaan_coauthor-physics_3450.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data coauthor-physics --epochs 50 --batch_size 8624 >>log/graphsage_gaan_coauthor-physics_8624.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data coauthor-physics --epochs 50 --batch_size 17247 >>log/graphsage_gaan_coauthor-physics_17247.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data com-amazon --epochs 50 --batch_size 3349 >>log/graphsage_gcn_com-amazon_3349.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data com-amazon --epochs 50 --batch_size 10046 >>log/graphsage_gcn_com-amazon_10046.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data com-amazon --epochs 50 --batch_size 20092 >>log/graphsage_gcn_com-amazon_20092.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data com-amazon --epochs 50 --batch_size 33487 >>log/graphsage_gcn_com-amazon_33487.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data com-amazon --epochs 50 --batch_size 83716 >>log/graphsage_gcn_com-amazon_83716.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data com-amazon --epochs 50 --batch_size 167432 >>log/graphsage_gcn_com-amazon_167432.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data com-amazon --epochs 50 --batch_size 3349 >>log/graphsage_ggnn_com-amazon_3349.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data com-amazon --epochs 50 --batch_size 10046 >>log/graphsage_ggnn_com-amazon_10046.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data com-amazon --epochs 50 --batch_size 20092 >>log/graphsage_ggnn_com-amazon_20092.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data com-amazon --epochs 50 --batch_size 33487 >>log/graphsage_ggnn_com-amazon_33487.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data com-amazon --epochs 50 --batch_size 83716 >>log/graphsage_ggnn_com-amazon_83716.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data com-amazon --epochs 50 --batch_size 167432 >>log/graphsage_ggnn_com-amazon_167432.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data com-amazon --epochs 50 --batch_size 3349 >>log/graphsage_gat_com-amazon_3349.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data com-amazon --epochs 50 --batch_size 10046 >>log/graphsage_gat_com-amazon_10046.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data com-amazon --epochs 50 --batch_size 20092 >>log/graphsage_gat_com-amazon_20092.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data com-amazon --epochs 50 --batch_size 33487 >>log/graphsage_gat_com-amazon_33487.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data com-amazon --epochs 50 --batch_size 83716 >>log/graphsage_gat_com-amazon_83716.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data com-amazon --epochs 50 --batch_size 167432 >>log/graphsage_gat_com-amazon_167432.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data com-amazon --epochs 50 --batch_size 3349 >>log/graphsage_gaan_com-amazon_3349.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data com-amazon --epochs 50 --batch_size 10046 >>log/graphsage_gaan_com-amazon_10046.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data com-amazon --epochs 50 --batch_size 20092 >>log/graphsage_gaan_com-amazon_20092.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data com-amazon --epochs 50 --batch_size 33487 >>log/graphsage_gaan_com-amazon_33487.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data com-amazon --epochs 50 --batch_size 83716 >>log/graphsage_gaan_com-amazon_83716.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data com-amazon --epochs 50 --batch_size 167432 >>log/graphsage_gaan_com-amazon_167432.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data pubmed --epochs 50 --batch_size 198 >>log/graphsage_gcn_pubmed_198.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data pubmed --epochs 50 --batch_size 592 >>log/graphsage_gcn_pubmed_592.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data pubmed --epochs 50 --batch_size 1184 >>log/graphsage_gcn_pubmed_1184.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data pubmed --epochs 50 --batch_size 1972 >>log/graphsage_gcn_pubmed_1972.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data pubmed --epochs 50 --batch_size 4930 >>log/graphsage_gcn_pubmed_4930.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gcn --data pubmed --epochs 50 --batch_size 9859 >>log/graphsage_gcn_pubmed_9859.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data pubmed --epochs 50 --batch_size 198 >>log/graphsage_ggnn_pubmed_198.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data pubmed --epochs 50 --batch_size 592 >>log/graphsage_ggnn_pubmed_592.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data pubmed --epochs 50 --batch_size 1184 >>log/graphsage_ggnn_pubmed_1184.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data pubmed --epochs 50 --batch_size 1972 >>log/graphsage_ggnn_pubmed_1972.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data pubmed --epochs 50 --batch_size 4930 >>log/graphsage_ggnn_pubmed_4930.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model ggnn --data pubmed --epochs 50 --batch_size 9859 >>log/graphsage_ggnn_pubmed_9859.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data pubmed --epochs 50 --batch_size 198 >>log/graphsage_gat_pubmed_198.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data pubmed --epochs 50 --batch_size 592 >>log/graphsage_gat_pubmed_592.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data pubmed --epochs 50 --batch_size 1184 >>log/graphsage_gat_pubmed_1184.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data pubmed --epochs 50 --batch_size 1972 >>log/graphsage_gat_pubmed_1972.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data pubmed --epochs 50 --batch_size 4930 >>log/graphsage_gat_pubmed_4930.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gat --data pubmed --epochs 50 --batch_size 9859 >>log/graphsage_gat_pubmed_9859.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data pubmed --epochs 50 --batch_size 198 >>log/graphsage_gaan_pubmed_198.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data pubmed --epochs 50 --batch_size 592 >>log/graphsage_gaan_pubmed_592.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data pubmed --epochs 50 --batch_size 1184 >>log/graphsage_gaan_pubmed_1184.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data pubmed --epochs 50 --batch_size 1972 >>log/graphsage_gaan_pubmed_1972.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data pubmed --epochs 50 --batch_size 4930 >>log/graphsage_gaan_pubmed_4930.log 2>&1
python -m code.main_sampling_graph_info --device cuda:2 --mode graphsage --model gaan --data pubmed --epochs 50 --batch_size 9859 >>log/graphsage_gaan_pubmed_9859.log 2>&1
